---
# tasks file for frontail

- name: Pull/update the frontail docker image
  tags: frontail
  docker_container:
    detach: True
    hostname: "{{ frontail_hostname }}"
    image: welteki/frontail-openhab:{{ frontail_version }}
    name: frontail
    network_mode: host
    pull: True
    state: started
    interactive: yes
    restart: true
    restart_policy: always
    tty: True
    volumes:
      - "{{ frontail_openhab_home }}/userdata/logs:/var/log/openhab:ro"
  register: frontail_pulled
