# invoke with `ansible-playbook openhab-play.yml -i ./hosts --vault-id openhab@prompt`

- name: playbook to set up an openHAB server on a Raspberry Pi
  hosts: openhab
  gather_facts: false
  debugger: on_failed
  become: true

  tasks:
    - include_role: 
        name: roles/prepare-raspberry
    - include_role:
        name: roles/weareinteractive.git
        vars:
        git_config:
            user:
            name: "{{ git_commit_user_name }}"
            email: "{{ git_commit_user_email }}"
            submodule:
            recurse: true
            push:
            recursesubmodules: on-demand
            status:
            submodulesummary: 1
    - include_role: 
        name: roles/geerlingguy.pip
    - include_role: 
        name: roles/geerlingguy.docker_arm
    - name: roles/reboot host
      reboot:
    - include_role: 
        name: roles/openhab
      vars:
        system_user: "{{ user_name }}"
    - include_role:
        name: roles/frontail
    - include_role:
        name: roles/minimize-writes
    - include_role:
        name: roles/bertvv.samba
    - name: SSH into openHAB folder
      blockinfile:
        path: /home/{{ user_name }}/.bashrc
        block: |
          # on login jump to openhab directory
          cd {{ openhab_home }}/openhab